version: '3.6'

services:
  training-frontend-vue:
    image: nginx
    container_name: "frontend_vue"
    ports:
     - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./dist:/var/www/app
    # restart: always

networks:
  default:
    name: training-network
